server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    
spring:

    
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  mail:
    host: smtp.gmail.com
    port: 587
    username: helpringproject@gmail.com
    password: drgvyvvgrnihypbg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      

          
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.72.50/helpring?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #show-sql: true
      format-sql: true

  profiles.active: oauth

file:
  dir:   C:\Users\juyoung\git\Helpring\src\main\resources\static\post_upload\
  lecture_dir: C:\Users\juyoung\git\Helpring\src\main\resources\static\lecture_upload\
  course_dir: C:\Users\juyoung\git\Helpring\src\main\resources\static\course_upload\

logging:
  level:
    org.hibernate.SQL: debug
  #org.hibernate.type: trace
