server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mustache:
    prefix: classpath:/templates/
    expose-request-attributes: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: helpringservice@gmail.com
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helpring?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #show-sql: true
      format-sql: true

  profiles.active: oauth

file:
  dir: C:\intellij\workspace\helpring\helpring\src\main\resources\static\post_upload\

logging:
  level:
    org.hibernate.SQL: debug
  #org.hibernate.type: trace

---
spring.config.activate.on-profile: oauth

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 423276194391-i8nbbv34mk4r2m7f8agovrfg919cl6nq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: h9fZGPt1x7vdYsqrqAwG
            client-secret: XDffhlKckJ
            scope:
              - name
              - email
              - nickname
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 key값으로 naver가 리턴해줌